CREATE DATABASE IF NOT EXISTS moodify;

USE moodify;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  username VARCHAR(100),
  spotify_id VARCHAR(255),
  mood VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
